### ISSUE TITLE
Error in onEnable on version 2.2

### ISSUE THREAD

**Issue by TitoGuapito** [TCPShield/RealIP#21] opened 2020-10-02 14:41 UTC
```
[09:36:25] [Server thread/ERROR]: Error occurred while enabling TCPShield v2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
	at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:14) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:git-Spigot-17d78db-5c77bd2]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
	... 11 more
```
This is the error I get when trying to use the plugin. I use spigot 1.16.3 (the newest), in BungeeCord the plugin is working.
Succes with solving!

**Comment by JosiahWhite** [comment] 2020-10-02 14:42
Duplicate of #20

**Closed as completed by JosiahWhite** 2020-10-02 14:42 UTC
