### ISSUE TITLE
Error while enabling TCPShield v2.2

### ISSUE THREAD

**Issue by averwhy** [TCPShield/RealIP#10] opened 2020-07-26 01:20 UTC
I added the plugin to my 1.16.1 Paper server (paper 111) and i found this in console:
```
[21:14:50 ERROR]: Error occurred while enabling TCPShield v2.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener
        at net.tcpshield.tcpshield.bukkit.TCPShieldBukkit.onEnable(TCPShieldBukkit.java:14) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-111]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-111]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-111]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-111]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-111]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-111]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-111]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-111]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-111]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.1.jar:git-Paper-111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.1.jar:git-Paper-111]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 11 more
```
This is the latest released version, so is it a problem with paper? Should i attach my whole startup log?

**Comment by paulzhng** [comment] 2020-07-26 12:07
Install ProtocolLib and the error should be fixed. Native Paper support is for the time being disabled

**Closed as completed by paulzhng** 2020-07-26 12:07 UTC

**Comment by averwhy** [comment] 2020-07-27 03:15
That worked. Thanks @Fuzzlemann

**Comment by ArnarPallK** [comment] 2023-03-29 01:11
> Install ProtocolLib and the error should be fixed. Native Paper support is for the time being disabled

That actually didn't work for me and I always had ProtocoLib installed. I have the same error message for TCPShield and then a whole list of errors from ProtocoLib.
`[01:01:23 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v4.8.0
[01:01:23 WARN]: [ProtocolLib] Version (MC: 1.19.4) has not yet been tested! Proceed with caution.
[01:01:26 ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.ExceptionInInitializerError
        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185)
        at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177)
        at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59)
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18)
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36)
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36)
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:1623)
  Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @1747df90
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
        at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161)
        at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187)
        at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51)
        ... 14 more
  Dump:
  Parameters:
    [NULL]
  Sender:
    com.comphenix.protocol.ProtocolLib@b67d531[
      statistics=<null>
      backgroundCompiler=<null>
      packetTask=-1
      tickCounter=0
      unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77cd2690
      configExpectedMod=-1
      updater=com.comphenix.protocol.updater.SpigotUpdater@42b6bb05
      redirectHandler=<null>
      commandProtocol=<null>
      commandPacket=<null>
      commandFilter=<null>
      packetLogging=<null>
      skipDisable=false
      isEnabled=false
      loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1cdfa45
      server=CraftServer{serverName=Paper,serverVersion=git-Paper-474,minecraftVersion=1.19.4}
      file=plugins\ProtocolLib.jar
      description=org.bukkit.plugin.PluginDescriptionFile@39dc5af7
      pluginMeta=org.bukkit.plugin.PluginDescriptionFile@39dc5af7
      dataFolder=plugins\ProtocolLib
      classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib.jar}
      naggable=true
      newConfig=YamlConfiguration[path='', root='YamlConfiguration']
      configFile=plugins\ProtocolLib\config.yml
      logger=com.destroystokyo.paper.utils.PaperPluginLogger@33b16585
    ]
  Version:
    ProtocolLib v4.8.0
  Java Version:
    20
  Server:
    git-Paper-474 (MC: 1.19.4)`
`[01:01:37 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[01:01:37 ERROR]: ******************************************************
[01:01:37 ERROR]: *** ProtocolLib does not support plugin reloaders! ***
[01:01:37 ERROR]: *** Please use the built-in reload command!        ***
[01:01:37 ERROR]: ******************************************************
[01:01:37 INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0`

**Comment by DylanKeir** [comment] 2023-03-29 06:21
> > Install ProtocolLib and the error should be fixed. Native Paper support is for the time being disabled
> 
> That actually didn't work for me and I always had ProtocoLib installed. I have the same error message for TCPShield and then a whole list of errors from ProtocoLib. `[01:01:23 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v4.8.0 [01:01:23 WARN]: [ProtocolLib] Version (MC: 1.19.4) has not yet been tested! Proceed with caution. [01:01:26 ERROR]: [ProtocolLib] INTERNAL ERROR: Cannot load ProtocolLib. If this problem hasn't already been reported, please open a ticket at https://github.com/dmulloy2/ProtocolLib/issues with the following data: Stack Trace: java.lang.ExceptionInInitializerError at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ProtocolInjector.<init>(ProtocolInjector.java:69) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterManager.<init>(PacketFilterManager.java:202) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.buildInternal(PacketFilterBuilder.java:185) at ProtocolLib.jar//com.comphenix.protocol.injector.PacketFilterBuilder.build(PacketFilterBuilder.java:177) at ProtocolLib.jar//com.comphenix.protocol.ProtocolLib.onLoad(ProtocolLib.java:203) at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:273) at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104) at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) at java.base/java.lang.Thread.run(Thread.java:1623) Caused by: java.lang.UnsupportedOperationException: Cannot define class using reflection: Unable to make protected java.lang.Package java.lang.ClassLoader.getPackage(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module @1747df90 at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$Initializable$Unavailable.defineClass(ClassInjector.java:471) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:117) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$InjectionDispatcher.load(ClassLoadingStrategy.java:243) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:150) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101) at ProtocolLib.jar//com.comphenix.net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6161) at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.setupProxyPlayerConstructor(TemporaryPlayerFactory.java:187) at ProtocolLib.jar//com.comphenix.protocol.injector.server.TemporaryPlayerFactory.<clinit>(TemporaryPlayerFactory.java:51) ... 14 more Dump: Parameters: [NULL] Sender: com.comphenix.protocol.ProtocolLib@b67d531[ statistics=<null> backgroundCompiler=<null> packetTask=-1 tickCounter=0 unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@77cd2690 configExpectedMod=-1 updater=com.comphenix.protocol.updater.SpigotUpdater@42b6bb05 redirectHandler=<null> commandProtocol=<null> commandPacket=<null> commandFilter=<null> packetLogging=<null> skipDisable=false isEnabled=false loader=io.papermc.paper.plugin.manager.DummyBukkitPluginLoader@1cdfa45 server=CraftServer{serverName=Paper,serverVersion=git-Paper-474,minecraftVersion=1.19.4} file=plugins\ProtocolLib.jar description=org.bukkit.plugin.PluginDescriptionFile@39dc5af7 pluginMeta=org.bukkit.plugin.PluginDescriptionFile@39dc5af7 dataFolder=plugins\ProtocolLib classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=false, url=plugins\ProtocolLib.jar} naggable=true newConfig=YamlConfiguration[path='', root='YamlConfiguration'] configFile=plugins\ProtocolLib\config.yml logger=com.destroystokyo.paper.utils.PaperPluginLogger@33b16585 ] Version: ProtocolLib v4.8.0 Java Version: 20 Server: git-Paper-474 (MC: 1.19.4)` `[01:01:37 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0 [01:01:37 ERROR]: ****************************************************** [01:01:37 ERROR]: *** ProtocolLib does not support plugin reloaders! *** [01:01:37 ERROR]: *** Please use the built-in reload command! *** [01:01:37 ERROR]: ****************************************************** [01:01:37 INFO]: [ProtocolLib] Disabling ProtocolLib v4.8.0`

Looks like you're using an old version of the TCPShield plugin, re-try with the latest version. https://github.com/TCPShield/RealIP/releases/tag/2.6.1
